name: apk_exercicio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  http: ^1.5.0
  splash_master: ^0.0.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images.png

splash_master:
  color: '#083D77'
  image: 'assets/images.png'
  android_gravity: 'center'

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images.png'